import type { Promisable } from '@subframe7536/type-utils'
import type { Plugin, ResolvedConfig } from 'vite'

import MagicString from 'magic-string'
import fs from 'node:fs'
import path from 'node:path'
import { normalizePath } from 'vite'

import { bytecodeId, bytecodeLog } from '../constant'
import { readableSize } from '../utils/file'
import { bytecodeModuleLoaderCode } from './code'
import {
  bytecodeModuleLoader,
  compileToBytecode,
  prepare,
  toRelativePath,
  useStrict,
} from './utils'

/** Options for bytecode compilation */
export interface BytecodeOptions {
  /** Enable bytecode compilation */
  enable: boolean
  /**
   * Enable in preload script. Remember to set `sandbox: false` when creating window
   */
  preload?: boolean
  /**
   * Custom electron binary path for bytecode generation
   */
  electronPath?: string
  /**
   * Before transformed code compile function. If return `Falsy` value, it will be ignored
   * @param code - Transformed code
   * @param id - File path
   * @returns Transformed code or falsy to ignore
   */
  beforeCompile?: (code: string, id: string) => Promisable<string | null | undefined | void>
}

function getBytecodeLoaderBlock(chunkFileName: string): string {
  return `require("${toRelativePath(bytecodeModuleLoader, normalizePath(chunkFileName))}");`
}

function checkHasBytecodeChunk(
  getModuleInfo: (id: string) => { importers: string[]; dynamicImporters: string[] } | null,
  imports: string[],
  dynamicImports: string[],
  bytecodeChunks: Set<string>,
): boolean {
  const queue = [...imports, ...dynamicImports]
  const visited = new Set<string>()

  while (queue.length > 0) {
    const moduleId = queue.shift()!
    if (visited.has(moduleId)) {
      continue
    }
    visited.add(moduleId)

    if (bytecodeChunks.has(moduleId)) {
      return true
    }

    const moduleInfo = getModuleInfo(moduleId)
    // if (moduleInfo && !moduleInfo.isExternal) {
    if (moduleInfo) {
      const { importers, dynamicImporters } = moduleInfo
      for (const importerId of importers) {
        if (!visited.has(importerId)) {
          queue.push(importerId)
        }
      }
      for (const importerId of dynamicImporters) {
        if (!visited.has(importerId)) {
          queue.push(importerId)
        }
      }
    }
  }

  return false
}

/**
 * Vite plugin that compiles JavaScript files to V8 bytecode for source code protection.
 *
 * This plugin transforms JavaScript files into bytecode format during build,
 * making the source code more difficult to reverse engineer. The generated bytecode
 * files (.jsc) can only be executed in compatible Electron environments.
 *
 * @param env - Environment type ('preload' | 'main')
 * @param options - Bytecode compilation options
 * @returns Vite plugin or null if bytecode compilation is disabled
 */
export function bytecodePlugin(
  env: 'preload' | 'main',
  minify: boolean,
  isESM: boolean,
  options: BytecodeOptions,
): Plugin | null {
  const { enable, preload = false, electronPath, beforeCompile } = options

  if (!enable) {
    return null
  }

  if (!preload && env === 'preload') {
    bytecodeLog.warn(
      '`bytecodePlugin` is skiped in preload. To enable in preload, please manually set the "enablePreload" option to true and set `sandbox: false` when creating the window',
      { timestamp: true },
    )
    return null
  }

  if (isESM) {
    throw new Error(
      '`bytecodePlugin` does not support ES module, please set `"types": "commonjs"` in package.json',
    )
  }

  let config: ResolvedConfig
  let bytecodeRequired = false
  let bytecodeFiles: { name: string; size: number }[] = []

  return {
    name: `${bytecodeId}-${env}`,
    apply: 'build',
    enforce: 'post',
    configResolved(resolvedConfig) {
      config = resolvedConfig
    },
    renderChunk(_, chunk) {
      if (chunk.type === 'chunk') {
        bytecodeRequired = true
      }
      return null
    },
    generateBundle(): void {
      if (bytecodeRequired) {
        this.emitFile({
          type: 'asset',
          source: `${bytecodeModuleLoaderCode}\n`,
          name: 'Bytecode Loader File',
          fileName: bytecodeModuleLoader,
        })
      }
    },
    async writeBundle(options, output) {
      if (!bytecodeRequired) {
        return
      }

      const outDir = options.dir!
      bytecodeFiles = []

      const bundles = Object.keys(output)
      const chunks = Object.values(output).filter(
        (chunk) => chunk.type === 'chunk' && chunk.fileName !== bytecodeModuleLoader,
      ) as any[]
      const bytecodeChunks = new Set(chunks.map((chunk) => chunk.fileName))
      const nonEntryChunks = chunks
        .filter((chunk) => !chunk.isEntry)
        .map((chunk) => path.basename(chunk.fileName))

      const pattern = nonEntryChunks.map((chunk) => `(${chunk})`).join('|')
      const bytecodeRE = pattern ? new RegExp(`require\\(\\S*(?=(${pattern})\\S*\\))`, 'g') : null

      await Promise.all(
        bundles.map(async (name) => {
          const chunk = output[name]
          if (chunk.type === 'chunk') {
            let _code = prepare(chunk.code, minify)
            const chunkFilePath = path.join(outDir, name)

            if (bytecodeRE && _code.match(bytecodeRE)) {
              let match: RegExpExecArray | null
              const s = new MagicString(_code)
              // eslint-disable-next-line no-cond-assign
              while ((match = bytecodeRE.exec(_code))) {
                const [prefix, chunkName] = match
                const len = prefix.length + chunkName.length
                s.overwrite(match.index, match.index + len, `${prefix + chunkName}c`, {
                  contentOnly: true,
                })
              }
              _code = s.toString()
            }

            if (beforeCompile) {
              const cbResult = await beforeCompile(_code, chunkFilePath)
              if (cbResult) {
                _code = cbResult
              }
            }

            if (bytecodeChunks.has(name)) {
              const result = await compileToBytecode(
                _code,
                path.join(outDir, chunk.fileName),
                electronPath,
              )
              if (typeof result === 'string') {
                throw new Error(result)
              }
              fs.writeFileSync(`${chunkFilePath}c`, result)

              if (chunk.isEntry) {
                const bytecodeLoaderBlock = getBytecodeLoaderBlock(chunk.fileName)
                const bytecodeModuleBlock = `require("./${`${path.basename(name)}c`}");`
                const code = `${useStrict}\n${bytecodeLoaderBlock}\nmodule.exports=${bytecodeModuleBlock}\n`
                fs.writeFileSync(chunkFilePath, code)
              } else {
                fs.unlinkSync(chunkFilePath)
              }

              bytecodeFiles.push({ name: `${name}c`, size: result.length })
            } else if (chunk.isEntry) {
              const hasBytecodeMoudle = checkHasBytecodeChunk(
                this.getModuleInfo,
                chunk.imports,
                chunk.dynamicImports,
                bytecodeChunks,
              )
              if (hasBytecodeMoudle) {
                const bytecodeLoaderBlock = getBytecodeLoaderBlock(chunk.fileName)
                _code = _code.replace(/use strict(["'];)/, `$1\n${bytecodeLoaderBlock}`)
              }
              fs.writeFileSync(chunkFilePath, _code)
            } else {
              fs.writeFileSync(chunkFilePath, _code)
            }
          }
        }),
      )
    },
    closeBundle() {
      const outDir = `${normalizePath(path.relative(config.root, path.resolve(config.root, config.build.outDir)))}/`
      bytecodeFiles.forEach((file) => {
        bytecodeLog.info(`${outDir}${file.name} [${readableSize(file.size)}]`, { timestamp: true })
      })
      bytecodeLog.info(`${bytecodeFiles.length} bundles compiled into bytecode.`, {
        timestamp: true,
      })
      bytecodeFiles = []
    },
  }
}
